In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 10)

In [3]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr ** arr

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489])

In [7]:
arr / arr

/var/folders/lk/0c4x8qpx44v2mf75zt7j71b80000gn/T/ipykernel_64341/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [8]:
1 / arr

/var/folders/lk/0c4x8qpx44v2mf75zt7j71b80000gn/T/ipykernel_64341/1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [9]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [10]:
np.log(arr)

/var/folders/lk/0c4x8qpx44v2mf75zt7j71b80000gn/T/ipykernel_64341/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [11]:
arr.sum()

45

In [12]:
arr.mean()

4.5

In [13]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [14]:
arr.var()

8.25

In [15]:
arr.std()

2.8722813232690143

In [17]:
arr_2d = np.arange(0, 25).reshape(5, 5)

In [18]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
arr_2d.sum(axis = 0)

array([50, 55, 60, 65, 70])

In [20]:
arr_2d.sum(axis = 1)

array([ 10,  35,  60,  85, 110])