In [1]:
import numpy as np

In [4]:
mylist = [1, 2, 3]

In [5]:
type(mylist)

list

In [7]:
np.array(mylist)

array([1, 2, 3])

In [8]:
myarr = np.array(mylist)

In [9]:
type(myarr)

numpy.ndarray

In [10]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
type(my_matrix)

list

In [12]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
my_triple_matrix = [[[1], [2], [3]], [[4], [5], [6]], [[7], [8], [9]]]

In [14]:
np.array(my_triple_matrix)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [15]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [28]:
len(np.linspace(1, 10, 10))

10

In [31]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
np.random.rand(5,4)

array([[0.93376362, 0.04149702, 0.07928447, 0.29453156],
       [0.70176726, 0.91880616, 0.36792699, 0.68467407],
       [0.75091662, 0.88420789, 0.89884563, 0.80857532],
       [0.22578663, 0.03540989, 0.1703452 , 0.16860732],
       [0.57813393, 0.43877648, 0.07839766, 0.71024389]])

In [36]:
np.random.randn(2, 3)

array([[ 0.48087466,  0.6418671 , -1.84060732],
       [ 1.4039053 , -1.32743454, -0.97917757]])

In [41]:
np.random.randint(0,101, (4,5))

array([[12, 75, 71, 39, 21],
       [23, 79, 47, 81, 98],
       [84, 60, 52, 25, 58],
       [37,  5, 63, 50,  3]])

In [43]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [44]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [45]:
arr = np.arange(0, 25)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [47]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
ranarr = np.random.randint(0, 101, 10)

In [49]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [51]:
ranarr.max()

99

In [52]:
ranarr.min()

2

In [53]:
ranarr.argmax()

5

In [54]:
ranarr.argmin()

7

In [55]:
ranarr.dtype

dtype('int64')

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [57]:
arr.shape

(25,)

In [58]:
ranarr.shape

(10,)

In [61]:
arr = arr.reshape(5, 5)

In [62]:
arr.shape

(5, 5)

In [65]:
arr = arr.reshape(25, 1)

In [66]:
arr.shape

(25, 1)